<?php

/**
 * @file
 * Module implementation file.
 */

use Drupal\Core\Routing\RouteObjectInterface;

/**
 * Implements hook_file_url_alter().
 */
function cl_server_file_url_alter(&$uri) {
  $request = \Drupal::request();
  $route_name = $request->attributes->get(RouteObjectInterface::ROUTE_NAME);

  // Only modify the URI if our controller is returning a response, and we are
  // not returning a URL to a file in the public files directory, notably
  // aggregated CSS and JS.
  if ($route_name === 'cl_server.render' && !str_starts_with($uri, 'public://')) {
    $uri = implode('/', [$request->getSchemeAndHttpHost(), ltrim($uri, '/')]);
  }
}
