<?php

/**
 * @file
 * Contains customy.module.
 */

/**
 * Implements hook_page_attachments().
 */
function customy_page_attachments(array &$page) {
//  $page['#attached']['library'][] = 'entrypoints/app';
}

/**
 * Implements hook_update_N().
 */
function customy_update_1001() {
  // Disable modules.
  $modules_to_dsable = [
    "xray_audit",
    "editoria11y"
  ];

  foreach ($modules_to_dsable as $module) {
    if (\Drupal::moduleHandler()->moduleExists($module)) {
      \Drupal::moduleHandler()->disable([$module]);
      drupal_flush_all_caches();
      \Drupal::logger('customy')->notice('Disabled the "@module" module.', ['@module' => $module]);
    }
  }
}
