package_name:
  type: string
  label: 'Package name'
  constraints:
    Regex:
      # @see https://getcomposer.org/schema.json
      pattern: '/^[a-z0-9]([_.-]?[a-z0-9]+)*/[a-z0-9](([_.]|-{1,2})?[a-z0-9]+)*$/'

package_manager.settings:
  type: config_object
  label: 'Package Manager settings'
  mapping:
    file_syncer:
      type: string
      label: 'Which file syncer to use, or NULL to auto-detect'
    executables:
      type: sequence
      label: 'Absolute paths to required executables, or NULL to rely on PATH'
      sequence:
        type: string
        label: 'Absolute path to executable, or NULL'
    additional_trusted_composer_plugins:
      type: sequence
      label: 'Additional trusted composer plugins'
      sequence:
        type: package_name
        label: 'Trusted composer plugin'
